#!/usr/bin/env node
/**
 * Main_Test: runs all E2E specs and produces a detailed report.
 * Usage: node scripts/Main_Test.mjs [--base-url URL]
 * Output: TestReport_YYYYMMDD_HHMMSS.md
 */

import { spawnSync } from 'child_process'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')
const reportPath = path.join(root, 'e2e-results.json')
const outputDir = path.join(root, '..', 'TestReports')

const baseUrl = process.env.BASE_URL || process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:3000'

function runPlaywright() {
  const env = { ...process.env, BASE_URL: baseUrl, PLAYWRIGHT_BASE_URL: baseUrl }
  const r = spawnSync('npx', ['playwright', 'test'], {
    cwd: root,
    env,
    encoding: 'utf-8',
    shell: true,
  })
  return r
}

function parseReport() {
  if (!fs.existsSync(reportPath)) return null
  const raw = fs.readFileSync(reportPath, 'utf-8')
  try {
    return JSON.parse(raw)
  } catch {
    return null
  }
}

function collectTests(data, acc = { byFile: new Map(), total: 0, passed: 0, failed: 0 }) {
  if (!data) return acc
  function walk(n, file) {
    if (n.specs) {
      for (const spec of n.specs) {
        const f = file || spec.file || 'unknown'
        const base = path.basename(String(f), '.spec.ts')
        if (!acc.byFile.has(base)) acc.byFile.set(base, [])
        for (const t of spec.tests || []) {
          acc.total++
          const ok = (t.results || []).some((r) => r.status === 'passed')
          if (ok) acc.passed++
          else acc.failed++
          const err = t.results?.find((r) => r.error)?.error?.message
          acc.byFile.get(base).push({ title: t.title || spec.title, ok, error: err })
        }
      }
    }
    for (const c of n.suites || []) walk(c, file || n.file)
  }
  if (Array.isArray(data.suites)) data.suites.forEach((s) => walk(s))
  else if (data.suites) walk(data.suites)
  return acc
}

function generateMarkdown(data) {
  const lines = []
  const ts = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  const reportFile = `TestReport_${ts}.md`

  lines.push('# E2E Test Report')
  lines.push('')
  lines.push(`**Generated:** ${new Date().toISOString()}`)
  lines.push(`**Base URL:** ${baseUrl}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  const collected = collectTests(data)
  const { byFile, total, passed, failed } = collected

  if (total === 0 && (!data || !data.suites)) {
    lines.push('## Summary')
    lines.push('')
    lines.push('No test results found. Run `npx playwright test` and ensure `e2e-results.json` is produced.')
    lines.push('')
    return { reportFile, content: lines.join('\n') }
  }

  lines.push('## Summary')
  lines.push('')
  lines.push(`| Metric | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total tests | ${total} |`)
  lines.push(`| Passed | ${passed} |`)
  lines.push(`| Failed | ${failed} |`)
  lines.push('')
  lines.push('---')
  lines.push('')

  lines.push('## Screens & features tested')
  lines.push('')

  const failedTests = []
  for (const [name, tests] of byFile) {
    lines.push(`### ${name}`)
    lines.push('')
    for (const t of tests) {
      const status = t.ok ? '✅' : '❌'
      lines.push(`- ${status} **${t.title}**`)
      if (!t.ok && t.error) {
        lines.push(`  - **Error:** ${t.error}`)
        lines.push(`  - **Possible reasons:** Network/timeout, missing element, redirect to login, API down, wrong base URL.`)
        failedTests.push({ ...t, file: name })
      } else if (!t.ok) failedTests.push({ ...t, file: name })
    }
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('## Issues found')
  lines.push('')

  if (failedTests.length === 0) {
    lines.push('None.')
  } else {
    for (const t of failedTests) {
      lines.push(`- **${t.title}** (${t.file})`)
      lines.push(`  - ${t.error || 'No error message'}`)
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('')
  lines.push('*Report generated by Main_Test. Run `npx playwright test` for full output.*')

  return { reportFile, content: lines.join('\n') }
}

function main() {
  console.log('Running Playwright E2E tests...')
  console.log('Base URL:', baseUrl)
  const result = runPlaywright()
  if (result.status !== 0) {
    console.log('Playwright exit code:', result.status)
    if (result.stderr) console.error(result.stderr)
  }

  const data = parseReport()
  const { reportFile, content } = generateMarkdown(data)

  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true })
  const outPath = path.join(outputDir, reportFile)
  fs.writeFileSync(outPath, content, 'utf-8')
  console.log('Report written to:', outPath)

  process.exit(result.status !== 0 ? 1 : 0)
}

main()
